In [3]:
###@features of pandas@###
    data structures
    data cleaning
    indexing and slicing
    data aggregation
    data transformation
    time series handling
    data visualization
    integration
    file I/O
    pandas  series objects are size is immutable
    but it allows to modify element value
    it only allows homegenous objects




In [7]:
# import pandas
import pandas as pd

In [9]:
# Create pandas series using list

data = [10, 20, 30, 40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [11]:
# Create series using a custom index
data = [1,2,3,4]
i = ['A', 'B', 'C', 'D']
series = pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [15]:
## Create a pandas series using dictionary
data = {'a': 10, 'b': 20, 'c': 30}
series = pd.Series(data)
print(series)

a    10
b    20
c    30
dtype: int64


In [17]:
series.replace(20,40)

a    10
b    40
c    30
dtype: int64

In [21]:
# create series using numpy array
import numpy as np

data = np.array([100, 200, 300])
series = pd.Series(data, index=['a','b','c'])
print(series)

a    100
b    200
c    300
dtype: int32


In [ ]:
# pandas dataframe

In [23]:
#  create pandas dataframe from dictionary of lists
import pandas as pd

data = {'Name': ['Alice', 'Bob','Mary'], 'Age': [25, 30, 34], 'Country':["USA","UK","AUS"]}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   25     USA
1    Bob   30      UK
2   Mary   34     AUS


In [29]:
# create pandas dataframe from numpy array

import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)
df = pd.DataFrame(array, columns=['A', 'B', 'C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
